apiVersion: v1
kind: Namespace
metadata:
  name: sample-controller
---
apiVersion: samplecontroller.k8s.io/v1alpha1
kind: Foo
metadata:
  name: example-foo
  namespace: sample-controller
spec:
  deploymentName: example-foo
  replicas: 1
